In [1]:
#set dependicies
import pandas as pd
import requests
import json
import numpy as np

from config import api_key

In [2]:
#base url for EIA solar energy
##Change to BTUs!!!
base_url = f"http://api.eia.gov/category/?api_key={api_key}&category_id="

residential_id = "2811027"
commercial_id = "45562"
industrial_id = "45564"

query_url = (base_url + residential_id)

residential_response = requests.get(query_url).json()
residential_response

{'request': {'category_id': 2811027, 'command': 'category'},
 'category': {'category_id': '2811027',
  'parent_category_id': '2804526',
  'name': 'Physical Units',
  'notes': '',
  'childcategories': [],
  'childseries': [{'series_id': 'SEDS.SOR7P.AK.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Alaska',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.AL.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Alabama',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.AR.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Arkansas',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.AZ.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Arizona',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.CA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, California',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.CO.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Colorado',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.CT.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Connecticut',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.DC.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, District of Columbia',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.DE.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Delaware',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.FL.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Florida',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.GA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Georgia',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.HI.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Hawaii',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.IA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Iowa',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.ID.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Idaho',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.IL.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Illinois',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.IN.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Indiana',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.KS.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Kansas',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.KY.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Kentucky',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.LA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Louisiana',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.MA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Massachusetts',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.MD.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Maryland',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.ME.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Maine',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.MI.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Michigan',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.MN.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Minnesota',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.MO.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Missouri',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.MS.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Mississippi',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.MT.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Montana',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.NC.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, North Carolina',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.ND.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, North Dakota',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.NE.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Nebraska',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.NH.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, New Hampshire',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.NJ.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, New Jersey',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.NM.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, New Mexico',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.NV.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Nevada',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.NY.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, New York',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.OH.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Ohio',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.OK.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Oklahoma',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.OR.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Oregon',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.PA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Pennsylvania',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.RI.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Rhode Island',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.SC.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, South Carolina',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.SD.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, South Dakota',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.TN.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Tennessee',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.TX.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Texas',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.US.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, United States',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.UT.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Utah',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.VA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Virginia',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.VT.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Vermont',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.WA.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Washington',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.WI.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Wisconsin',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.WV.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, West Virginia',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SOR7P.WY.A',
    'name': 'Solar photovoltaic electricity generation by small-scale applications in the residential sector, Wyoming',
    'f': 'A',
    'units': 'Million kilowatthours',
    'updated': '29-MAY-20 10.39.12 PM'}]}}

In [3]:
state_id = residential_response["category"]["childseries"][51]["series_id"]
state_id

'SEDS.SOR7P.WY.A'

In [94]:
#iterate through the json list to pull each state
#need to drop DC.  US = entire united states
indices = np.arange(0,52,1)
state_id = residential_response["category"]["childseries"][0]["series_id"]
state_list = []

for x in range(len(indices)):
    state_id = residential_response["category"]["childseries"][indices[x]]["series_id"]
    state_list.append(state_id)

state_list

['SEDS.SOR7P.AK.A',
 'SEDS.SOR7P.AL.A',
 'SEDS.SOR7P.AR.A',
 'SEDS.SOR7P.AZ.A',
 'SEDS.SOR7P.CA.A',
 'SEDS.SOR7P.CO.A',
 'SEDS.SOR7P.CT.A',
 'SEDS.SOR7P.DC.A',
 'SEDS.SOR7P.DE.A',
 'SEDS.SOR7P.FL.A',
 'SEDS.SOR7P.GA.A',
 'SEDS.SOR7P.HI.A',
 'SEDS.SOR7P.IA.A',
 'SEDS.SOR7P.ID.A',
 'SEDS.SOR7P.IL.A',
 'SEDS.SOR7P.IN.A',
 'SEDS.SOR7P.KS.A',
 'SEDS.SOR7P.KY.A',
 'SEDS.SOR7P.LA.A',
 'SEDS.SOR7P.MA.A',
 'SEDS.SOR7P.MD.A',
 'SEDS.SOR7P.ME.A',
 'SEDS.SOR7P.MI.A',
 'SEDS.SOR7P.MN.A',
 'SEDS.SOR7P.MO.A',
 'SEDS.SOR7P.MS.A',
 'SEDS.SOR7P.MT.A',
 'SEDS.SOR7P.NC.A',
 'SEDS.SOR7P.ND.A',
 'SEDS.SOR7P.NE.A',
 'SEDS.SOR7P.NH.A',
 'SEDS.SOR7P.NJ.A',
 'SEDS.SOR7P.NM.A',
 'SEDS.SOR7P.NV.A',
 'SEDS.SOR7P.NY.A',
 'SEDS.SOR7P.OH.A',
 'SEDS.SOR7P.OK.A',
 'SEDS.SOR7P.OR.A',
 'SEDS.SOR7P.PA.A',
 'SEDS.SOR7P.RI.A',
 'SEDS.SOR7P.SC.A',
 'SEDS.SOR7P.SD.A',
 'SEDS.SOR7P.TN.A',
 'SEDS.SOR7P.TX.A',
 'SEDS.SOR7P.US.A',
 'SEDS.SOR7P.UT.A',
 'SEDS.SOR7P.VA.A',
 'SEDS.SOR7P.VT.A',
 'SEDS.SOR7P.WA.A',
 'SEDS.SOR7P.WI.A',
 'SEDS.SOR7P.WV.A',
 'SEDS.SOR7P.WY.A']

In [104]:
#get data from 1 state
state_id = "SEDS.SOR7P.NC.A"

series_url = f"http://api.eia.gov/series/?api_key={api_key}&series_id="
query_url = (series_url + state_id)

index2 = np.arange(0,20,1)
year_list = []
consumption_list = []

for x in range(len(index2)):
    year = requests.get(query_url).json()['series'][0]['data'][0:20][index2[x]][0]
    consumption = requests.get(query_url).json()['series'][0]['data'][0:20][index2[x]][1]
    year_list.append(year)
    consumption_list.append(consumption)

print(year_list)
print(consumption_list)

['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999']
[89, 67, 51, 19, 11, 5, 3, 3, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [105]:
#loop through the states
state_id = state_list
years = ['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999']


series_url = f"http://api.eia.gov/series/?api_key={api_key}&series_id="
index2 = np.arange(0,20,1)
year=[]
consumption_list = []
for state in state_id:
    query_url = (series_url + state)
    state_response = requests.get(query_url).json()
    
    for x in range(len(index2)):
        year = state_response['series'][0]['data'][0:20][index2[x]][0]
        consumption = state_response['series'][0]['data'][0:20][index2[x]][1]
        year_list.append(year)
        consumption_list.append(consumption)

In [106]:
AK=consumption_list[0:20]
AL=consumption_list[20:40]
AR=consumption_list[40:60]
AZ=consumption_list[60:80]
CA=consumption_list[80:100]
CO=consumption_list[100:120]
CT=consumption_list[120:140]
DC=consumption_list[140:160]
DE=consumption_list[160:180]
FL=consumption_list[180:200]
GA=consumption_list[200:220]
HI=consumption_list[220:240]
IA=consumption_list[240:260]
ID=consumption_list[260:280]
IL=consumption_list[280:300]
IN=consumption_list[300:320]
KS=consumption_list[320:340]
KY=consumption_list[340:360]
LA=consumption_list[360:380]
MA=consumption_list[380:400]
MD=consumption_list[400:420]
ME=consumption_list[420:440]
MI=consumption_list[440:460]
MN=consumption_list[460:480]
MO=consumption_list[480:500]
MS=consumption_list[500:520]
MT=consumption_list[520:540]
NC=consumption_list[540:560]
ND=consumption_list[560:580]
NE=consumption_list[580:600]
NH=consumption_list[600:620]
NJ=consumption_list[620:640]
NM=consumption_list[640:660]
NV=consumption_list[660:680]
NY=consumption_list[680:700]
OH=consumption_list[700:720]
OK=consumption_list[720:740]
OR=consumption_list[740:760]
PA=consumption_list[760:780]
RI=consumption_list[780:800]
SC=consumption_list[800:820]
SD=consumption_list[820:840]
TN=consumption_list[840:860]
TX=consumption_list[860:880]
US=consumption_list[880:900]
UT=consumption_list[900:920]
VA=consumption_list[920:940]
VT=consumption_list[940:960]
WA=consumption_list[960:980]
WI=consumption_list[980:1000]
WV=consumption_list[1000:1020]
WY=consumption_list[1020:1040]

In [119]:
df = pd.DataFrame({"year": years, "AK": AK, "AL":AL, "AR":AR, "AZ":AZ, "CA":CA, "CO":CO, "CT":CT, "DC":DC, "DE":DE, "FL":FL,
                   "GA":GA, "HI":HI, "IA":IA, "ID":ID, "IL":IL, "KS":KS, "KY":KY, "LA":LA, "MA":MA, "MD":MD, "ME":ME, "MI":MI,
                   "MN":MN, "MO":MO, "MS":MS, "MT":MT, "NC":NC, "ND":ND, "NE":NE, "NH": NH, "NJ":NJ, "NM":NM, "NV":NV, "NY":NY,
                   "OH":OH, "OK":OK, "OR":OR, "PA":PA,"RI":RI, "SC":SC, "SD":SD, "TN":TN, "TX":TX, "US":US, "UT":UT, "VA":VA,
                   "VT":VT, "WA":WA, "WI":WI, "WV":WV, "WY":WY})

df

,year,AK,AL,AR,AZ,CA,CO,CT,DC,DE,...,TN,TX,US,UT,VA,VT,WA,WI,WV,WY
0,2018,2,3,13,1511,7851,366,276,29,69,...,25,528,17105,307,58,81,126,32,7,4
1,2017,1,2,6,1241,6529,317,230,23,59,...,23,345,13942,218,41,70,97,24,6,3
2,2016,1,2,4,964,5147,265,174,16,40,...,22,252,10595,101,25,51,76,16,4,2
3,2015,0,0,3,721,3528,210,98,10,22,...,0,126,6999,36,16,36,46,10,3,2
4,2014,0,0,2,536,2494,177,52,8,16,...,0,93,4947,16,11,25,28,7,3,1
5,2013,0,0,2,375,1569,124,27,6,12,...,0,65,3217,9,8,17,16,6,3,1
6,2012,0,0,2,246,1012,88,17,5,9,...,0,40,2058,5,6,11,10,5,2,1
7,2011,0,0,1,142,733,65,13,4,6,...,0,25,1358,3,5,5,5,4,0,0
8,2010,0,0,1,84,521,49,10,2,4,...,0,14,900,1,3,2,3,3,0,0
9,2009,0,0,0,31,359,29,6,0,2,...,0,7,539,0,1,2,1,2,0,0
10,2008,0,0,0,11,291,17,4,0,1,...,0,4,401,0,1,1,0,1,0,0
11,2007,0,0,0,5,187,6,2,0,1,...,0,2,250,0,0,1,0,1,0,0
12,2006,0,0,0,2,136,3,1,0,0,...,0,2,177,0,0,0,0,1,0,0
13,2005,0,0,0,1,90,2,1,0,0,...,0,1,121,0,0,0,0,0,0,0
14,2004,0,0,0,1,60,1,0,0,0,...,0,1,81,0,0,0,0,0,0,0
15,2003,0,0,0,1,48,1,0,0,0,...,0,1,65,0,0,0,0,0,0,0
16,2002,0,0,0,1,41,1,0,0,0,...,0,0,56,0,0,0,0,0,0,0
17,2001,0,0,0,1,35,1,0,0,0,...,0,0,47,0,0,0,0,0,0,0
18,2000,0,0,0,0,29,1,0,0,0,...,0,0,39,0,0,0,0,0,0,0
19,1999,0,0,0,0,25,1,0,0,0,...,0,0,34,0,0,0,0,0,0,0

In [122]:
df.set_index("year", inplace = True)
df

,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FL,...,TN,TX,US,UT,VA,VT,WA,WI,WV,WY
year,,,,,,,,,,,,,,,,,,,,,
2018,2,3,13,1511,7851,366,276,29,69,308,...,25,528,17105,307,58,81,126,32,7,4
2017,1,2,6,1241,6529,317,230,23,59,190,...,23,345,13942,218,41,70,97,24,6,3
2016,1,2,4,964,5147,265,174,16,40,116,...,22,252,10595,101,25,51,76,16,4,2
2015,0,0,3,721,3528,210,98,10,22,79,...,0,126,6999,36,16,36,46,10,3,2
2014,0,0,2,536,2494,177,52,8,16,55,...,0,93,4947,16,11,25,28,7,3,1
2013,0,0,2,375,1569,124,27,6,12,38,...,0,65,3217,9,8,17,16,6,3,1
2012,0,0,2,246,1012,88,17,5,9,25,...,0,40,2058,5,6,11,10,5,2,1
2011,0,0,1,142,733,65,13,4,6,17,...,0,25,1358,3,5,5,5,4,0,0
2010,0,0,1,84,521,49,10,2,4,12,...,0,14,900,1,3,2,3,3,0,0
2009,0,0,0,31,359,29,6,0,2,8,...,0,7,539,0,1,2,1,2,0,0
2008,0,0,0,11,291,17,4,0,1,2,...,0,4,401,0,1,1,0,1,0,0
2007,0,0,0,5,187,6,2,0,1,1,...,0,2,250,0,0,1,0,1,0,0
2006,0,0,0,2,136,3,1,0,0,0,...,0,2,177,0,0,0,0,1,0,0
2005,0,0,0,1,90,2,1,0,0,0,...,0,1,121,0,0,0,0,0,0,0
2004,0,0,0,1,60,1,0,0,0,0,...,0,1,81,0,0,0,0,0,0,0
2003,0,0,0,1,48,1,0,0,0,0,...,0,1,65,0,0,0,0,0,0,0
2002,0,0,0,1,41,1,0,0,0,0,...,0,0,56,0,0,0,0,0,0,0
2001,0,0,0,1,35,1,0,0,0,0,...,0,0,47,0,0,0,0,0,0,0
2000,0,0,0,0,29,1,0,0,0,0,...,0,0,39,0,0,0,0,0,0,0
1999,0,0,0,0,25,1,0,0,0,0,...,0,0,34,0,0,0,0,0,0,0

In [123]:
residential_solar_df = df.T

residential_solar_df

year,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,1999
AK,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AL,3,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AR,13,6,4,3,2,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0
AZ,1511,1241,964,721,536,375,246,142,84,31,11,5,2,1,1,1,1,1,0,0
CA,7851,6529,5147,3528,2494,1569,1012,733,521,359,291,187,136,90,60,48,41,35,29,25
CO,366,317,265,210,177,124,88,65,49,29,17,6,3,2,1,1,1,1,1,1
CT,276,230,174,98,52,27,17,13,10,6,4,2,1,1,0,0,0,0,0,0
DC,29,23,16,10,8,6,5,4,2,0,0,0,0,0,0,0,0,0,0,0
DE,69,59,40,22,16,12,9,6,4,2,1,1,0,0,0,0,0,0,0,0
FL,308,190,116,79,55,38,25,17,12,8,2,1,0,0,0,0,0,0,0,0
GA,17,16,13,6,4,3,2,1,1,0,0,0,0,0,0,0,0,0,0,0
HI,620,609,479,389,323,246,123,43,18,5,1,1,1,1,0,0,0,0,0,0
IA,43,31,20,13,8,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ID,27,12,7,4,2,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0
IL,34,21,13,8,5,4,4,2,2,1,1,1,0,0,0,0,0,0,0,0
KS,17,11,6,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
KY,12,10,7,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
LA,214,192,184,147,99,58,22,8,3,0,0,0,0,0,0,0,0,0,0,0
MA,724,547,414,211,128,59,30,14,8,6,3,2,1,1,1,1,1,0,0,0
MD,580,498,310,143,76,30,13,6,2,0,0,0,0,0,0,0,0,0,0,0
ME,36,27,19,13,9,9,4,0,0,0,0,0,0,0,0,0,0,0,0,0
MI,34,31,24,10,8,6,5,3,1,0,0,0,0,0,0,0,0,0,0,0
MN,43,30,18,10,8,5,4,2,2,1,1,1,0,0,0,0,0,0,0,0
MO,118,97,75,59,48,25,8,0,0,0,0,0,0,0,0,0,0,0,0,0
MS,4,3,2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MT,14,11,8,6,9,9,6,2,2,2,2,1,1,0,0,0,0,0,0,0
NC,89,67,51,19,11,5,3,3,3,2,1,0,0,0,0,0,0,0,0,0
ND,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
NE,6,3,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
NH,69,56,36,16,9,6,3,2,2,1,0,0,0,0,0,0,0,0,0,0
NJ,827,684,491,337,284,203,153,104,59,35,30,21,16,12,8,7,6,5,4,4
NM,168,128,92,69,52,41,23,13,6,3,1,0,0,0,0,0,0,0,0,0
NV,357,287,253,99,32,17,11,8,7,4,3,2,1,1,1,0,0,0,0,0
NY,868,733,547,319,162,77,56,42,32,21,16,9,7,7,4,4,3,3,2,2
OH,34,27,20,14,10,9,5,2,1,1,1,0,0,0,0,0,0,0,0,0
OK,7,4,3,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
OR,104,85,67,47,36,27,22,15,9,4,3,2,2,1,1,1,1,0,0,0
PA,207,163,109,93,88,83,72,57,30,3,1,1,1,1,0,0,0,0,0,0
RI,44,28,14,3,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
SC,163,92,24,5,3,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0
SD,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
TN,25,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
TX,528,345,252,126,93,65,40,25,14,7,4,2,2,1,1,1,0,0,0,0
US,17105,13942,10595,6999,4947,3217,2058,1358,900,539,401,250,177,121,81,65,56,47,39,34
UT,307,218,101,36,16,9,5,3,1,0,0,0,0,0,0,0,0,0,0,0
VA,58,41,25,16,11,8,6,5,3,1,1,0,0,0,0,0,0,0,0,0
VT,81,70,51,36,25,17,11,5,2,2,1,1,0,0,0,0,0,0,0,0
WA,126,97,76,46,28,16,10,5,3,1,0,0,0,0,0,0,0,0,0,0
WI,32,24,16,10,7,6,5,4,3,2,1,1,1,0,0,0,0,0,0,0
WV,7,6,4,3,3,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0
WY,4,3,2,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [129]:
residential_solar_df.index.names=["State"]
residential_solar_df

year,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,1999
State,,,,,,,,,,,,,,,,,,,,
AK,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AL,3,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AR,13,6,4,3,2,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0
AZ,1511,1241,964,721,536,375,246,142,84,31,11,5,2,1,1,1,1,1,0,0
CA,7851,6529,5147,3528,2494,1569,1012,733,521,359,291,187,136,90,60,48,41,35,29,25
CO,366,317,265,210,177,124,88,65,49,29,17,6,3,2,1,1,1,1,1,1
CT,276,230,174,98,52,27,17,13,10,6,4,2,1,1,0,0,0,0,0,0
DC,29,23,16,10,8,6,5,4,2,0,0,0,0,0,0,0,0,0,0,0
DE,69,59,40,22,16,12,9,6,4,2,1,1,0,0,0,0,0,0,0,0
FL,308,190,116,79,55,38,25,17,12,8,2,1,0,0,0,0,0,0,0,0
GA,17,16,13,6,4,3,2,1,1,0,0,0,0,0,0,0,0,0,0,0
HI,620,609,479,389,323,246,123,43,18,5,1,1,1,1,0,0,0,0,0,0
IA,43,31,20,13,8,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ID,27,12,7,4,2,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0
IL,34,21,13,8,5,4,4,2,2,1,1,1,0,0,0,0,0,0,0,0
KS,17,11,6,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
KY,12,10,7,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
LA,214,192,184,147,99,58,22,8,3,0,0,0,0,0,0,0,0,0,0,0
MA,724,547,414,211,128,59,30,14,8,6,3,2,1,1,1,1,1,0,0,0
MD,580,498,310,143,76,30,13,6,2,0,0,0,0,0,0,0,0,0,0,0
ME,36,27,19,13,9,9,4,0,0,0,0,0,0,0,0,0,0,0,0,0
MI,34,31,24,10,8,6,5,3,1,0,0,0,0,0,0,0,0,0,0,0
MN,43,30,18,10,8,5,4,2,2,1,1,1,0,0,0,0,0,0,0,0
MO,118,97,75,59,48,25,8,0,0,0,0,0,0,0,0,0,0,0,0,0
MS,4,3,2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MT,14,11,8,6,9,9,6,2,2,2,2,1,1,0,0,0,0,0,0,0
NC,89,67,51,19,11,5,3,3,3,2,1,0,0,0,0,0,0,0,0,0
ND,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
NE,6,3,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
NH,69,56,36,16,9,6,3,2,2,1,0,0,0,0,0,0,0,0,0,0
NJ,827,684,491,337,284,203,153,104,59,35,30,21,16,12,8,7,6,5,4,4
NM,168,128,92,69,52,41,23,13,6,3,1,0,0,0,0,0,0,0,0,0
NV,357,287,253,99,32,17,11,8,7,4,3,2,1,1,1,0,0,0,0,0
NY,868,733,547,319,162,77,56,42,32,21,16,9,7,7,4,4,3,3,2,2
OH,34,27,20,14,10,9,5,2,1,1,1,0,0,0,0,0,0,0,0,0
OK,7,4,3,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
OR,104,85,67,47,36,27,22,15,9,4,3,2,2,1,1,1,1,0,0,0
PA,207,163,109,93,88,83,72,57,30,3,1,1,1,1,0,0,0,0,0,0
RI,44,28,14,3,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
SC,163,92,24,5,3,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0
SD,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
TN,25,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
TX,528,345,252,126,93,65,40,25,14,7,4,2,2,1,1,1,0,0,0,0
US,17105,13942,10595,6999,4947,3217,2058,1358,900,539,401,250,177,121,81,65,56,47,39,34
UT,307,218,101,36,16,9,5,3,1,0,0,0,0,0,0,0,0,0,0,0
VA,58,41,25,16,11,8,6,5,3,1,1,0,0,0,0,0,0,0,0,0
VT,81,70,51,36,25,17,11,5,2,2,1,1,0,0,0,0,0,0,0,0
WA,126,97,76,46,28,16,10,5,3,1,0,0,0,0,0,0,0,0,0,0
WI,32,24,16,10,7,6,5,4,3,2,1,1,1,0,0,0,0,0,0,0
WV,7,6,4,3,3,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0
WY,4,3,2,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0