In [1]:
#set dependicies
import pandas as pd
import requests
import json
import numpy as np

from config import api_key

In [2]:
#base url for EIA solar energy
#Changed IDs to BTUs, units are billion BTUs
base_url = f"http://api.eia.gov/category/?api_key={api_key}&category_id="

#get category ids
residential_id = "2804527"
commercial_id = "45563"
industrial_id = "45565"

query_url = (base_url + residential_id)

residential_response = requests.get(query_url).json()
residential_response

{'request': {'category_id': 2804527, 'command': 'category'},
 'category': {'category_id': '2804527',
  'parent_category_id': '2804526',
  'name': 'Btu',
  'notes': '',
  'childcategories': [],
  'childseries': [{'series_id': 'SEDS.SORCB.AK.A',
    'name': 'Solar energy consumed by the residential sector, Alaska',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.AL.A',
    'name': 'Solar energy consumed by the residential sector, Alabama',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.AR.A',
    'name': 'Solar energy consumed by the residential sector, Arkansas',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.AZ.A',
    'name': 'Solar energy consumed by the residential sector, Arizona',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.CA.A',
    'name': 'Solar energy consumed by the residential sector, California',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.CO.A',
    'name': 'Solar energy consumed by the residential sector, Colorado',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.CT.A',
    'name': 'Solar energy consumed by the residential sector, Connecticut',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.DC.A',
    'name': 'Solar energy consumed by the residential sector, District of Columbia',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.DE.A',
    'name': 'Solar energy consumed by the residential sector, Delaware',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.FL.A',
    'name': 'Solar energy consumed by the residential sector, Florida',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.GA.A',
    'name': 'Solar energy consumed by the residential sector, Georgia',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.HI.A',
    'name': 'Solar energy consumed by the residential sector, Hawaii',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.IA.A',
    'name': 'Solar energy consumed by the residential sector, Iowa',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.ID.A',
    'name': 'Solar energy consumed by the residential sector, Idaho',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.IL.A',
    'name': 'Solar energy consumed by the residential sector, Illinois',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.IN.A',
    'name': 'Solar energy consumed by the residential sector, Indiana',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.KS.A',
    'name': 'Solar energy consumed by the residential sector, Kansas',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.KY.A',
    'name': 'Solar energy consumed by the residential sector, Kentucky',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.LA.A',
    'name': 'Solar energy consumed by the residential sector, Louisiana',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.MA.A',
    'name': 'Solar energy consumed by the residential sector, Massachusetts',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.MD.A',
    'name': 'Solar energy consumed by the residential sector, Maryland',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.ME.A',
    'name': 'Solar energy consumed by the residential sector, Maine',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.MI.A',
    'name': 'Solar energy consumed by the residential sector, Michigan',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.MN.A',
    'name': 'Solar energy consumed by the residential sector, Minnesota',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.MO.A',
    'name': 'Solar energy consumed by the residential sector, Missouri',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.MS.A',
    'name': 'Solar energy consumed by the residential sector, Mississippi',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.MT.A',
    'name': 'Solar energy consumed by the residential sector, Montana',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.NC.A',
    'name': 'Solar energy consumed by the residential sector, North Carolina',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.ND.A',
    'name': 'Solar energy consumed by the residential sector, North Dakota',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.NE.A',
    'name': 'Solar energy consumed by the residential sector, Nebraska',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.NH.A',
    'name': 'Solar energy consumed by the residential sector, New Hampshire',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.NJ.A',
    'name': 'Solar energy consumed by the residential sector, New Jersey',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.NM.A',
    'name': 'Solar energy consumed by the residential sector, New Mexico',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.NV.A',
    'name': 'Solar energy consumed by the residential sector, Nevada',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.NY.A',
    'name': 'Solar energy consumed by the residential sector, New York',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.OH.A',
    'name': 'Solar energy consumed by the residential sector, Ohio',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.OK.A',
    'name': 'Solar energy consumed by the residential sector, Oklahoma',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.OR.A',
    'name': 'Solar energy consumed by the residential sector, Oregon',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.PA.A',
    'name': 'Solar energy consumed by the residential sector, Pennsylvania',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.RI.A',
    'name': 'Solar energy consumed by the residential sector, Rhode Island',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.SC.A',
    'name': 'Solar energy consumed by the residential sector, South Carolina',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.SD.A',
    'name': 'Solar energy consumed by the residential sector, South Dakota',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.TN.A',
    'name': 'Solar energy consumed by the residential sector, Tennessee',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.TX.A',
    'name': 'Solar energy consumed by the residential sector, Texas',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.US.A',
    'name': 'Solar energy consumed by the residential sector, United States',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.UT.A',
    'name': 'Solar energy consumed by the residential sector, Utah',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.VA.A',
    'name': 'Solar energy consumed by the residential sector, Virginia',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.VT.A',
    'name': 'Solar energy consumed by the residential sector, Vermont',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.WA.A',
    'name': 'Solar energy consumed by the residential sector, Washington',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.WI.A',
    'name': 'Solar energy consumed by the residential sector, Wisconsin',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.WV.A',
    'name': 'Solar energy consumed by the residential sector, West Virginia',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'},
   {'series_id': 'SEDS.SORCB.WY.A',
    'name': 'Solar energy consumed by the residential sector, Wyoming',
    'f': 'A',
    'units': 'Billion Btu',
    'updated': '29-MAY-20 10.39.12 PM'}]}}

In [3]:
#iterate through the json list to pull each state
#need to drop DC.  US = entire united states
indices = np.arange(0,52,1)
state_id = residential_response["category"]["childseries"][0]["series_id"]
state_list = []

for x in range(len(indices)):
    state_id = residential_response["category"]["childseries"][indices[x]]["series_id"]
    state_list.append(state_id)

state_list

['SEDS.SORCB.AK.A',
 'SEDS.SORCB.AL.A',
 'SEDS.SORCB.AR.A',
 'SEDS.SORCB.AZ.A',
 'SEDS.SORCB.CA.A',
 'SEDS.SORCB.CO.A',
 'SEDS.SORCB.CT.A',
 'SEDS.SORCB.DC.A',
 'SEDS.SORCB.DE.A',
 'SEDS.SORCB.FL.A',
 'SEDS.SORCB.GA.A',
 'SEDS.SORCB.HI.A',
 'SEDS.SORCB.IA.A',
 'SEDS.SORCB.ID.A',
 'SEDS.SORCB.IL.A',
 'SEDS.SORCB.IN.A',
 'SEDS.SORCB.KS.A',
 'SEDS.SORCB.KY.A',
 'SEDS.SORCB.LA.A',
 'SEDS.SORCB.MA.A',
 'SEDS.SORCB.MD.A',
 'SEDS.SORCB.ME.A',
 'SEDS.SORCB.MI.A',
 'SEDS.SORCB.MN.A',
 'SEDS.SORCB.MO.A',
 'SEDS.SORCB.MS.A',
 'SEDS.SORCB.MT.A',
 'SEDS.SORCB.NC.A',
 'SEDS.SORCB.ND.A',
 'SEDS.SORCB.NE.A',
 'SEDS.SORCB.NH.A',
 'SEDS.SORCB.NJ.A',
 'SEDS.SORCB.NM.A',
 'SEDS.SORCB.NV.A',
 'SEDS.SORCB.NY.A',
 'SEDS.SORCB.OH.A',
 'SEDS.SORCB.OK.A',
 'SEDS.SORCB.OR.A',
 'SEDS.SORCB.PA.A',
 'SEDS.SORCB.RI.A',
 'SEDS.SORCB.SC.A',
 'SEDS.SORCB.SD.A',
 'SEDS.SORCB.TN.A',
 'SEDS.SORCB.TX.A',
 'SEDS.SORCB.US.A',
 'SEDS.SORCB.UT.A',
 'SEDS.SORCB.VA.A',
 'SEDS.SORCB.VT.A',
 'SEDS.SORCB.WA.A',
 'SEDS.SORCB.WI.A',
 'SEDS.SORCB.WV.A',
 'SEDS.SORCB.WY.A']

In [7]:
#test run to get json data
url = "http://api.eia.gov/series/?"
query_url = url + "api_key=" + api_key + "&series_id="
state = "SEDS.SORCB.NC.A"

response = requests.get(query_url + state).json()
response

{'request': {'command': 'series', 'series_id': 'SEDS.SORCB.NC.A'},
 'series': [{'series_id': 'SEDS.SORCB.NC.A',
   'name': 'Solar energy consumed by the residential sector, North Carolina',
   'units': 'Billion Btu',
   'f': 'A',
   'description': 'Solar energy consumed by the residential sector, North Carolina See http://www.eia.gov/state/seds/seds-technical-notes-complete.cfm?sid=US for technical notes and documentation.',
   'copyright': 'None',
   'source': 'SEDS, EIA, U.S. Energy Information Administration',
   'iso3166': 'USA-NC',
   'geography': 'USA-NC',
   'start': '1960',
   'end': '2018',
   'updated': '2020-05-29T22:39:12-0400',
   'data': [['2018', 1085],
    ['2017', 888],
    ['2016', 737],
    ['2015', 443],
    ['2014', 364],
    ['2013', 307],
    ['2012', 273],
    ['2011', 267],
    ['2010', 260],
    ['2009', 249],
    ['2008', 212],
    ['2007', 171],
    ['2006', 158],
    ['2005', 115],
    ['2004', 88],
    ['2003', 84],
    ['2002', 99],
    ['2001', 111],
    ['2000', 127],
    ['1999', 141],
    ['1998', 151],
    ['1997', 156],
    ['1996', 164],
    ['1995', 162],
    ['1994', 164],
    ['1993', 164],
    ['1992', 163],
    ['1991', 161],
    ['1990', 161],
    ['1989', 156],
    ['1988', 0],
    ['1987', 0],
    ['1986', 0],
    ['1985', 0],
    ['1984', 0],
    ['1983', 0],
    ['1982', 0],
    ['1981', 0],
    ['1980', 0],
    ['1979', 0],
    ['1978', 0],
    ['1977', 0],
    ['1976', 0],
    ['1975', 0],
    ['1974', 0],
    ['1973', 0],
    ['1972', 0],
    ['1971', 0],
    ['1970', 0],
    ['1969', 0],
    ['1968', 0],
    ['1967', 0],
    ['1966', 0],
    ['1965', 0],
    ['1964', 0],
    ['1963', 0],
    ['1962', 0],
    ['1961', 0],
    ['1960', 0]]}]}

In [4]:
#set up empty dictionary and lists
energy_consumption = {}
state_name = []
year = []
consumption = []

In [8]:
for row in state_list:
    url = "http://api.eia.gov/series/?"
    query_url = url + "api_key=" + api_key + "&series_id="

    response = requests.get(query_url + row).json()['series'][0]['data'][0:19]
    name_response = requests.get(query_url + row).json()['series'][0]['geography']
        
    for item in response:
        state_name.append(name_response)
        year.append(item[0])
        consumption.append(item[1])
        
    print(response)
    print(name_response)

[['2018', 19], ['2017', 13], ['2016', 10], ['2015', 3], ['2014', 3], ['2013', 3], ['2012', 3], ['2011', 3], ['2010', 3], ['2009', 3], ['2008', 2], ['2007', 0], ['2006', 0], ['2005', 0], ['2004', 0], ['2003', 0], ['2002', 0], ['2001', 0], ['2000', 0]]
USA-AK
[['2018', 100], ['2017', 97], ['2016', 94], ['2015', 76], ['2014', 75], ['2013', 73], ['2012', 69], ['2011', 67], ['2010', 65], ['2009', 62], ['2008', 64], ['2007', 63], ['2006', 62], ['2005', 53], ['2004', 54], ['2003', 68], ['2002', 82], ['2001', 97], ['2000', 113]]
USA-AL
[['2018', 187], ['2017', 124], ['2016', 103], ['2015', 92], ['2014', 87], ['2013', 85], ['2012', 81], ['2011', 71], ['2010', 69], ['2009', 59], ['2008', 53], ['2007', 53], ['2006', 94], ['2005', 90], ['2004', 239], ['2003', 367], ['2002', 500], ['2001', 642], ['2000', 795]]
USA-AR
[['2018', 17133], ['2017', 14788], ['2016', 12191], ['2015', 9971], ['2014', 8315], ['2013', 6709], ['2012', 5396], ['2011', 4353], ['2010', 3702], ['2009', 3116], ['2008', 2872], ['2007', 2628], ['2006', 2506], ['2005', 2425], ['2004', 2620], ['2003', 2748], ['2002', 2866], ['2001', 3076], ['2000', 3340]]
USA-AZ
[['2018', 89927], ['2017', 78486], ['2016', 65495], ['2015', 50656], ['2014', 41308], ['2013', 32066], ['2012', 26313], ['2011', 23338], ['2010', 20837], ['2009', 18864], ['2008', 18272], ['2007', 16999], ['2006', 15962], ['2005', 14979], ['2004', 15317], ['2003', 15490], ['2002', 15949], ['2001', 16646], ['2000', 17460]]
USA-CA
[['2018', 3621], ['2017', 3208], ['2016', 2734], ['2015', 2238], ['2014', 1963], ['2013', 1457], ['2012', 1105], ['2011', 891], ['2010', 726], ['2009', 523], ['2008', 398], ['2007', 276], ['2006', 226], ['2005', 202], ['2004', 191], ['2003', 197], ['2002', 203], ['2001', 210], ['2000', 219]]
USA-CO
[['2018', 3488], ['2017', 3090], ['2016', 2561], ['2015', 1857], ['2014', 1422], ['2013', 1163], ['2012', 1040], ['2011', 982], ['2010', 928], ['2009', 875], ['2008', 816], ['2007', 744], ['2006', 649], ['2005', 552], ['2004', 452], ['2003', 400], ['2002', 363], ['2001', 301], ['2000', 259]]
USA-CT
[['2018', 261], ['2017', 211], ['2016', 154], ['2015', 90], ['2014', 79], ['2013', 62], ['2012', 49], ['2011', 39], ['2010', 20], ['2009', 4], ['2008', 2], ['2007', 2], ['2006', 1], ['2005', 1], ['2004', 1], ['2003', 1], ['2002', 1], ['2001', 1], ['2000', 1]]
USA-DC
[['2018', 669], ['2017', 584], ['2016', 406], ['2015', 240], ['2014', 188], ['2013', 151], ['2012', 121], ['2011', 93], ['2010', 76], ['2009', 50], ['2008', 28], ['2007', 20], ['2006', 4], ['2005', 4], ['2004', 7], ['2003', 10], ['2002', 12], ['2001', 15], ['2000', 18]]
USA-DE
[['2018', 30466], ['2017', 29247], ['2016', 28020], ['2015', 27386], ['2014', 26894], ['2013', 26004], ['2012', 25248], ['2011', 24476], ['2010', 23732], ['2009', 23110], ['2008', 23598], ['2007', 23150], ['2006', 22984], ['2005', 22915], ['2004', 23956], ['2003', 24706], ['2002', 25656], ['2001', 26769], ['2000', 27909]]
USA-FL
[['2018', 494], ['2017', 478], ['2016', 448], ['2015', 381], ['2014', 361], ['2013', 339], ['2012', 323], ['2011', 308], ['2010', 293], ['2009', 281], ['2008', 258], ['2007', 245], ['2006', 241], ['2005', 237], ['2004', 234], ['2003', 236], ['2002', 231], ['2001', 226], ['2000', 224]]
USA-GA
[['2018', 7682], ['2017', 7634], ['2016', 6404], ['2015', 5585], ['2014', 5016], ['2013', 4238], ['2012', 3013], ['2011', 2207], ['2010', 1915], ['2009', 1750], ['2008', 1634], ['2007', 1441], ['2006', 1343], ['2005', 1285], ['2004', 1261], ['2003', 1250], ['2002', 1232], ['2001', 1230], ['2000', 1277]]
USA-HI
[['2018', 427], ['2017', 319], ['2016', 226], ['2015', 162], ['2014', 108], ['2013', 53], ['2012', 39], ['2011', 34], ['2010', 33], ['2009', 32], ['2008', 19], ['2007', 17], ['2006', 14], ['2005', 8], ['2004', 4], ['2003', 5], ['2002', 6], ['2001', 7], ['2000', 8]]
USA-IA
[['2018', 271], ['2017', 134], ['2016', 83], ['2015', 57], ['2014', 43], ['2013', 42], ['2012', 34], ['2011', 26], ['2010', 25], ['2009', 23], ['2008', 20], ['2007', 17], ['2006', 14], ['2005', 8], ['2004', 3], ['2003', 3], ['2002', 3], ['2001', 2], ['2000', 1]]
USA-ID
[['2018', 1583], ['2017', 1460], ['2016', 1365], ['2015', 1301], ['2014', 1264], ['2013', 1219], ['2012', 1189], ['2011', 1144], ['2010', 1106], ['2009', 1076], ['2008', 1022], ['2007', 921], ['2006', 791], ['2005', 653], ['2004', 508], ['2003', 383], ['2002', 318], ['2001', 241], ['2000', 202]]
USA-IL
[['2018', 420], ['2017', 303], ['2016', 230], ['2015', 198], ['2014', 177], ['2013', 163], ['2012', 149], ['2011', 140], ['2010', 133], ['2009', 128], ['2008', 102], ['2007', 100], ['2006', 91], ['2005', 78], ['2004', 63], ['2003', 37], ['2002', 38], ['2001', 35], ['2000', 33]]
USA-IN
[['2018', 182], ['2017', 132], ['2016', 83], ['2015', 51], ['2014', 41], ['2013', 40], ['2012', 30], ['2011', 26], ['2010', 25], ['2009', 24], ['2008', 23], ['2007', 24], ['2006', 21], ['2005', 17], ['2004', 15], ['2003', 18], ['2002', 22], ['2001', 25], ['2000', 29]]
USA-KS
[['2018', 185], ['2017', 161], ['2016', 138], ['2015', 90], ['2014', 81], ['2013', 79], ['2012', 67], ['2011', 64], ['2010', 62], ['2009', 60], ['2008', 48], ['2007', 41], ['2006', 39], ['2005', 35], ['2004', 30], ['2003', 4], ['2002', 4], ['2001', 4], ['2000', 4]]
USA-KY
[['2018', 2041], ['2017', 1860], ['2016', 1790], ['2015', 1465], ['2014', 1035], ['2013', 643], ['2012', 299], ['2011', 162], ['2010', 111], ['2009', 83], ['2008', 79], ['2007', 77], ['2006', 67], ['2005', 65], ['2004', 65], ['2003', 60], ['2002', 56], ['2001', 57], ['2000', 60]]
USA-LA
[['2018', 6901], ['2017', 5344], ['2016', 4118], ['2015', 2264], ['2014', 1507], ['2013', 846], ['2012', 560], ['2011', 407], ['2010', 339], ['2009', 309], ['2008', 266], ['2007', 224], ['2006', 191], ['2005', 174], ['2004', 169], ['2003', 146], ['2002', 152], ['2001', 158], ['2000', 177]]
USA-MA
[['2018', 5400], ['2017', 4703], ['2016', 2976], ['2015', 1445], ['2014', 836], ['2013', 392], ['2012', 230], ['2011', 158], ['2010', 119], ['2009', 98], ['2008', 82], ['2007', 75], ['2006', 69], ['2005', 65], ['2004', 61], ['2003', 36], ['2002', 39], ['2001', 40], ['2000', 43]]
USA-MD
[['2018', 481], ['2017', 396], ['2016', 323], ['2015', 265], ['2014', 234], ['2013', 229], ['2012', 172], ['2011', 134], ['2010', 130], ['2009', 127], ['2008', 127], ['2007', 116], ['2006', 109], ['2005', 97], ['2004', 96], ['2003', 89], ['2002', 96], ['2001', 103], ['2000', 110]]
USA-ME
[['2018', 821], ['2017', 791], ['2016', 716], ['2015', 586], ['2014', 566], ['2013', 534], ['2012', 514], ['2011', 476], ['2010', 446], ['2009', 426], ['2008', 408], ['2007', 405], ['2006', 335], ['2005', 274], ['2004', 224], ['2003', 199], ['2002', 210], ['2001', 219], ['2000', 229]]
USA-MI
[['2018', 612], ['2017', 492], ['2016', 373], ['2015', 306], ['2014', 281], ['2013', 252], ['2012', 237], ['2011', 212], ['2010', 205], ['2009', 190], ['2008', 183], ['2007', 143], ['2006', 146], ['2005', 141], ['2004', 172], ['2003', 203], ['2002', 226], ['2001', 257], ['2000', 288]]
USA-MN
[['2018', 1104], ['2017', 927], ['2016', 724], ['2015', 578], ['2014', 490], ['2013', 269], ['2012', 103], ['2011', 31], ['2010', 30], ['2009', 28], ['2008', 35], ['2007', 34], ['2006', 30], ['2005', 33], ['2004', 46], ['2003', 61], ['2002', 77], ['2001', 94], ['2000', 111]]
USA-MO
[['2018', 49], ['2017', 46], ['2016', 32], ['2015', 16], ['2014', 21], ['2013', 21], ['2012', 14], ['2011', 13], ['2010', 13], ['2009', 12], ['2008', 12], ['2007', 11], ['2006', 9], ['2005', 9], ['2004', 9], ['2003', 9], ['2002', 9], ['2001', 9], ['2000', 9]]
USA-MS
[['2018', 136], ['2017', 110], ['2016', 80], ['2015', 61], ['2014', 96], ['2013', 94], ['2012', 70], ['2011', 25], ['2010', 25], ['2009', 25], ['2008', 25], ['2007', 17], ['2006', 10], ['2005', 3], ['2004', 3], ['2003', 3], ['2002', 2], ['2001', 2], ['2000', 2]]
USA-MT
[['2018', 1085], ['2017', 888], ['2016', 737], ['2015', 443], ['2014', 364], ['2013', 307], ['2012', 273], ['2011', 267], ['2010', 260], ['2009', 249], ['2008', 212], ['2007', 171], ['2006', 158], ['2005', 115], ['2004', 88], ['2003', 84], ['2002', 99], ['2001', 111], ['2000', 127]]
USA-NC
[['2018', 7], ['2017', 7], ['2016', 7], ['2015', 7], ['2014', 7], ['2013', 7], ['2012', 5], ['2011', 4], ['2010', 4], ['2009', 4], ['2008', 3], ['2007', 3], ['2006', 3], ['2005', 2], ['2004', 1], ['2003', 1], ['2002', 1], ['2001', 1], ['2000', 1]]
USA-ND

[['2018', 85], ['2017', 59], ['2016', 45], ['2015', 37], ['2014', 35], ['2013', 34], ['2012', 31], ['2011', 29], ['2010', 26], ['2009', 25], ['2008', 25], ['2007', 23], ['2006', 20], ['2005', 15], ['2004', 11], ['2003', 12], ['2002', 12], ['2001', 13], ['2000', 14]]
USA-NE
[['2018', 702], ['2017', 588], ['2016', 402], ['2015', 217], ['2014', 152], ['2013', 126], ['2012', 98], ['2011', 87], ['2010', 79], ['2009', 67], ['2008', 59], ['2007', 51], ['2006', 45], ['2005', 40], ['2004', 35], ['2003', 25], ['2002', 28], ['2001', 30], ['2000', 33]]
USA-NH
[['2018', 9345], ['2017', 8110], ['2016', 6301], ['2015', 4887], ['2014', 4429], ['2013', 3621], ['2012', 3097], ['2011', 2605], ['2010', 2123], ['2009', 1852], ['2008', 1819], ['2007', 1700], ['2006', 1559], ['2005', 1396], ['2004', 1256], ['2003', 1078], ['2002', 845], ['2001', 576], ['2000', 566]]
USA-NJ
[['2018', 1741], ['2017', 1385], ['2016', 1051], ['2015', 842], ['2014', 693], ['2013', 587], ['2012', 404], ['2011', 311], ['2010', 236], ['2009', 199], ['2008', 183], ['2007', 163], ['2006', 173], ['2005', 177], ['2004', 238], ['2003', 286], ['2002', 326], ['2001', 371], ['2000', 429]]
USA-NM
[['2018', 4324], ['2017', 3714], ['2016', 3382], ['2015', 1959], ['2014', 1330], ['2013', 1156], ['2012', 1075], ['2011', 1024], ['2010', 985], ['2009', 933], ['2008', 906], ['2007', 850], ['2006', 773], ['2005', 679], ['2004', 589], ['2003', 576], ['2002', 561], ['2001', 528], ['2000', 469]]
USA-NV
[['2018', 9265], ['2017', 8105], ['2016', 6372], ['2015', 4285], ['2014', 2836], ['2013', 1999], ['2012', 1760], ['2011', 1600], ['2010', 1472], ['2009', 1341], ['2008', 1255], ['2007', 1089], ['2006', 958], ['2005', 805], ['2004', 651], ['2003', 561], ['2002', 549], ['2001', 538], ['2000', 539]]
USA-NY
[['2018', 586], ['2017', 524], ['2016', 458], ['2015', 402], ['2014', 366], ['2013', 342], ['2012', 298], ['2011', 267], ['2010', 251], ['2009', 240], ['2008', 192], ['2007', 168], ['2006', 162], ['2005', 154], ['2004', 144], ['2003', 126], ['2002', 116], ['2001', 98], ['2000', 98]]
USA-OH
[['2018', 93], ['2017', 70], ['2016', 57], ['2015', 50], ['2014', 42], ['2013', 41], ['2012', 31], ['2011', 28], ['2010', 26], ['2009', 25], ['2008', 24], ['2007', 22], ['2006', 20], ['2005', 21], ['2004', 27], ['2003', 35], ['2002', 44], ['2001', 53], ['2000', 63]]
USA-OK
[['2018', 2349], ['2017', 2179], ['2016', 1991], ['2015', 1792], ['2014', 1681], ['2013', 1562], ['2012', 1475], ['2011', 1377], ['2010', 1282], ['2009', 1211], ['2008', 1150], ['2007', 1035], ['2006', 866], ['2005', 738], ['2004', 678], ['2003', 674], ['2002', 659], ['2001', 652], ['2000', 631]]
USA-OR
[['2018', 2644], ['2017', 2250], ['2016', 1743], ['2015', 1593], ['2014', 1557], ['2013', 1492], ['2012', 1370], ['2011', 1220], ['2010', 940], ['2009', 659], ['2008', 598], ['2007', 542], ['2006', 486], ['2005', 426], ['2004', 401], ['2003', 364], ['2002', 396], ['2001', 407], ['2000', 436]]
USA-PA
[['2018', 444], ['2017', 302], ['2016', 170], ['2015', 64], ['2014', 54], ['2013', 53], ['2012', 52], ['2011', 47], ['2010', 46], ['2009', 45], ['2008', 45], ['2007', 37], ['2006', 33], ['2005', 23], ['2004', 21], ['2003', 23], ['2002', 26], ['2001', 29], ['2000', 32]]
USA-RI
[['2018', 1517], ['2017', 881], ['2016', 256], ['2015', 85], ['2014', 62], ['2013', 48], ['2012', 44], ['2011', 39], ['2010', 37], ['2009', 34], ['2008', 30], ['2007', 23], ['2006', 19], ['2005', 19], ['2004', 20], ['2003', 21], ['2002', 22], ['2001', 22], ['2000', 23]]
USA-SC
[['2018', 11], ['2017', 10], ['2016', 8], ['2015', 6], ['2014', 6], ['2013', 6], ['2012', 6], ['2011', 5], ['2010', 5], ['2009', 5], ['2008', 4], ['2007', 4], ['2006', 4], ['2005', 3], ['2004', 3], ['2003', 3], ['2002', 3], ['2001', 0], ['2000', 0]]
USA-SD
[['2018', 256], ['2017', 240], ['2016', 234], ['2015', 29], ['2014', 28], ['2013', 27], ['2012', 26], ['2011', 25], ['2010', 25], ['2009', 24], ['2008', 26], ['2007', 24], ['2006', 22], ['2005', 26], ['2004', 32], ['2003', 37], ['2002', 43], ['2001', 48], ['2000', 52]]
USA-TN
[['2018', 5407], ['2017', 3781], ['2016', 2915], ['2015', 1755], ['2014', 1457], ['2013', 1184], ['2012', 930], ['2011', 768], ['2010', 653], ['2009', 567], ['2008', 518], ['2007', 491], ['2006', 481], ['2005', 486], ['2004', 507], ['2003', 523], ['2002', 528], ['2001', 535], ['2000', 541]]
USA-TX
[['2018', 221244], ['2017', 193574], ['2016', 161652], ['2015', 128345], ['2014', 109530], ['2013', 91426], ['2012', 78841], ['2011', 70795], ['2010', 64714], ['2009', 59822], ['2008', 58436], ['2007', 55046], ['2006', 52501], ['2005', 50167], ['2004', 51130], ['2003', 51813], ['2002', 53293], ['2001', 55172], ['2000', 57707]]
USA
[['2018', 2856], ['2017', 2073], ['2016', 988], ['2015', 394], ['2014', 208], ['2013', 141], ['2012', 99], ['2011', 80], ['2010', 66], ['2009', 55], ['2008', 45], ['2007', 40], ['2006', 36], ['2005', 35], ['2004', 37], ['2003', 39], ['2002', 39], ['2001', 41], ['2000', 44]]
USA-UT
[['2018', 1074], ['2017', 918], ['2016', 766], ['2015', 678], ['2014', 624], ['2013', 581], ['2012', 550], ['2011', 525], ['2010', 500], ['2009', 465], ['2008', 453], ['2007', 396], ['2006', 329], ['2005', 267], ['2004', 209], ['2003', 190], ['2002', 178], ['2001', 146], ['2000', 136]]
USA-VA
[['2018', 830], ['2017', 737], ['2016', 566], ['2015', 423], ['2014', 325], ['2013', 245], ['2012', 190], ['2011', 128], ['2010', 104], ['2009', 94], ['2008', 82], ['2007', 58], ['2006', 50], ['2005', 42], ['2004', 37], ['2003', 34], ['2002', 31], ['2001', 29], ['2000', 29]]
USA-VT
[['2018', 1274], ['2017', 1020], ['2016', 828], ['2015', 549], ['2014', 386], ['2013', 271], ['2012', 211], ['2011', 163], ['2010', 137], ['2009', 120], ['2008', 107], ['2007', 101], ['2006', 108], ['2005', 116], ['2004', 155], ['2003', 190], ['2002', 227], ['2001', 262], ['2000', 289]]
USA-WA
[['2018', 533], ['2017', 464], ['2016', 388], ['2015', 334], ['2014', 305], ['2013', 284], ['2012', 273], ['2011', 259], ['2010', 238], ['2009', 223], ['2008', 203], ['2007', 166], ['2006', 147], ['2005', 140], ['2004', 152], ['2003', 167], ['2002', 174], ['2001', 183], ['2000', 195]]
USA-WI
[['2018', 117], ['2017', 106], ['2016', 92], ['2015', 82], ['2014', 75], ['2013', 73], ['2012', 66], ['2011', 52], ['2010', 46], ['2009', 44], ['2008', 46], ['2007', 43], ['2006', 40], ['2005', 38], ['2004', 38], ['2003', 27], ['2002', 30], ['2001', 33], ['2000', 36]]
USA-WV
[['2018', 41], ['2017', 28], ['2016', 20], ['2015', 16], ['2014', 15], ['2013', 15], ['2012', 12], ['2011', 6], ['2010', 6], ['2009', 4], ['2008', 5], ['2007', 4], ['2006', 4], ['2005', 3], ['2004', 2], ['2003', 2], ['2002', 2], ['2001', 2], ['2000', 2]]
USA-WY

In [26]:
df_info = {"State" : state_name, "Year" : year, "Consumption" : consumption}
df = pd.DataFrame(df_info)
df

      State  Year  Consumption
0    USA-AK  2018           19
1    USA-AK  2017           13
2    USA-AK  2016           10
3    USA-AK  2015            3
4    USA-AK  2014            3
..      ...   ...          ...
983  USA-WY  2004            2
984  USA-WY  2003            2
985  USA-WY  2002            2
986  USA-WY  2001            2
987  USA-WY  2000            2

[988 rows x 3 columns]

In [46]:
state = df["State"].unique()

y2018 = df.loc[df["Year"] == "2018",:]   
y2018_data = y2018["Consumption"].values

y2017 = df.loc[df["Year"] == "2017",:]   
y2017_data = y2017["Consumption"].values

y2016 = df.loc[df["Year"] == "2016",:]   
y2016_data = y2016["Consumption"].values

y2015 = df.loc[df["Year"] == "2015",:]   
y2015_data = y2015["Consumption"].values

y2014 = df.loc[df["Year"] == "2014",:]   
y2014_data = y2014["Consumption"].values

y2013 = df.loc[df["Year"] == "2013",:]   
y2013_data = y2013["Consumption"].values

y2012 = df.loc[df["Year"] == "2012",:]   
y2012_data = y2012["Consumption"].values

y2011 = df.loc[df["Year"] == "2011",:]   
y2011_data = y2011["Consumption"].values

y2010 = df.loc[df["Year"] == "2010",:]   
y2010_data = y2010["Consumption"].values

y2009 = df.loc[df["Year"] == "2009",:]   
y2009_data = y2009["Consumption"].values

y2008 = df.loc[df["Year"] == "2008",:]   
y2008_data = y2008["Consumption"].values

y2007 = df.loc[df["Year"] == "2007",:]   
y2007_data = y2007["Consumption"].values

y2006 = df.loc[df["Year"] == "2006",:]   
y2006_data = y2006["Consumption"].values

y2005 = df.loc[df["Year"] == "2005",:]   
y2005_data = y2005["Consumption"].values

y2004 = df.loc[df["Year"] == "2004",:]   
y2004_data = y2004["Consumption"].values

y2003 = df.loc[df["Year"] == "2003",:]   
y2003_data = y2003["Consumption"].values

y2002 = df.loc[df["Year"] == "2002",:]   
y2002_data = y2002["Consumption"].values

y2001 = df.loc[df["Year"] == "2001",:]   
y2001_data = y2001["Consumption"].values

y2000 = df.loc[df["Year"] == "2000",:]   
y2000_data = y2000["Consumption"].values

In [47]:
res_solar_df = pd.DataFrame({"State":state, "2018":y2018_data,"2017":y2017_data,"2016":y2016_data,"2015":y2015_data,
                             "2014":y2014_data,"2013":y2013_data,"2012":y2012_data,"2011":y2011_data,"2010":y2010_data,
                             "2009":y2009_data,"2008":y2008_data,"2007":y2007_data,"2006":y2006_data,"2005":y2005_data,
                             "2004":y2004_data,"2003":y2003_data,"2002":y2002_data,"2001":y2001_data,"2000":y2000_data
                            })
res_solar_df

,State,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,USA-AK,19,13,10,3,3,3,3,3,3,3,2,0,0,0,0,0,0,0,0
1,USA-AL,100,97,94,76,75,73,69,67,65,62,64,63,62,53,54,68,82,97,113
2,USA-AR,187,124,103,92,87,85,81,71,69,59,53,53,94,90,239,367,500,642,795
3,USA-AZ,17133,14788,12191,9971,8315,6709,5396,4353,3702,3116,2872,2628,2506,2425,2620,2748,2866,3076,3340
4,USA-CA,89927,78486,65495,50656,41308,32066,26313,23338,20837,18864,18272,16999,15962,14979,15317,15490,15949,16646,17460
5,USA-CO,3621,3208,2734,2238,1963,1457,1105,891,726,523,398,276,226,202,191,197,203,210,219
6,USA-CT,3488,3090,2561,1857,1422,1163,1040,982,928,875,816,744,649,552,452,400,363,301,259
7,USA-DC,261,211,154,90,79,62,49,39,20,4,2,2,1,1,1,1,1,1,1
8,USA-DE,669,584,406,240,188,151,121,93,76,50,28,20,4,4,7,10,12,15,18
9,USA-FL,30466,29247,28020,27386,26894,26004,25248,24476,23732,23110,23598,23150,22984,22915,23956,24706,25656,26769,27909
10,USA-GA,494,478,448,381,361,339,323,308,293,281,258,245,241,237,234,236,231,226,224
11,USA-HI,7682,7634,6404,5585,5016,4238,3013,2207,1915,1750,1634,1441,1343,1285,1261,1250,1232,1230,1277
12,USA-IA,427,319,226,162,108,53,39,34,33,32,19,17,14,8,4,5,6,7,8
13,USA-ID,271,134,83,57,43,42,34,26,25,23,20,17,14,8,3,3,3,2,1
14,USA-IL,1583,1460,1365,1301,1264,1219,1189,1144,1106,1076,1022,921,791,653,508,383,318,241,202
15,USA-IN,420,303,230,198,177,163,149,140,133,128,102,100,91,78,63,37,38,35,33
16,USA-KS,182,132,83,51,41,40,30,26,25,24,23,24,21,17,15,18,22,25,29
17,USA-KY,185,161,138,90,81,79,67,64,62,60,48,41,39,35,30,4,4,4,4
18,USA-LA,2041,1860,1790,1465,1035,643,299,162,111,83,79,77,67,65,65,60,56,57,60
19,USA-MA,6901,5344,4118,2264,1507,846,560,407,339,309,266,224,191,174,169,146,152,158,177
20,USA-MD,5400,4703,2976,1445,836,392,230,158,119,98,82,75,69,65,61,36,39,40,43
21,USA-ME,481,396,323,265,234,229,172,134,130,127,127,116,109,97,96,89,96,103,110
22,USA-MI,821,791,716,586,566,534,514,476,446,426,408,405,335,274,224,199,210,219,229
23,USA-MN,612,492,373,306,281,252,237,212,205,190,183,143,146,141,172,203,226,257,288
24,USA-MO,1104,927,724,578,490,269,103,31,30,28,35,34,30,33,46,61,77,94,111
25,USA-MS,49,46,32,16,21,21,14,13,13,12,12,11,9,9,9,9,9,9,9
26,USA-MT,136,110,80,61,96,94,70,25,25,25,25,17,10,3,3,3,2,2,2
27,USA-NC,1085,888,737,443,364,307,273,267,260,249,212,171,158,115,88,84,99,111,127
28,USA-ND,7,7,7,7,7,7,5,4,4,4,3,3,3,2,1,1,1,1,1
29,USA-NE,85,59,45,37,35,34,31,29,26,25,25,23,20,15,11,12,12,13,14
30,USA-NH,702,588,402,217,152,126,98,87,79,67,59,51,45,40,35,25,28,30,33
31,USA-NJ,9345,8110,6301,4887,4429,3621,3097,2605,2123,1852,1819,1700,1559,1396,1256,1078,845,576,566
32,USA-NM,1741,1385,1051,842,693,587,404,311,236,199,183,163,173,177,238,286,326,371,429
33,USA-NV,4324,3714,3382,1959,1330,1156,1075,1024,985,933,906,850,773,679,589,576,561,528,469
34,USA-NY,9265,8105,6372,4285,2836,1999,1760,1600,1472,1341,1255,1089,958,805,651,561,549,538,539
35,USA-OH,586,524,458,402,366,342,298,267,251,240,192,168,162,154,144,126,116,98,98
36,USA-OK,93,70,57,50,42,41,31,28,26,25,24,22,20,21,27,35,44,53,63
37,USA-OR,2349,2179,1991,1792,1681,1562,1475,1377,1282,1211,1150,1035,866,738,678,674,659,652,631
38,USA-PA,2644,2250,1743,1593,1557,1492,1370,1220,940,659,598,542,486,426,401,364,396,407,436
39,USA-RI,444,302,170,64,54,53,52,47,46,45,45,37,33,23,21,23,26,29,32
40,USA-SC,1517,881,256,85,62,48,44,39,37,34,30,23,19,19,20,21,22,22,23
41,USA-SD,11,10,8,6,6,6,6,5,5,5,4,4,4,3,3,3,3,0,0
42,USA-TN,256,240,234,29,28,27,26,25,25,24,26,24,22,26,32,37,43,48,52
43,USA-TX,5407,3781,2915,1755,1457,1184,930,768,653,567,518,491,481,486,507,523,528,535,541
44,USA,221244,193574,161652,128345,109530,91426,78841,70795,64714,59822,58436,55046,52501,50167,51130,51813,53293,55172,57707
45,USA-UT,2856,2073,988,394,208,141,99,80,66,55,45,40,36,35,37,39,39,41,44
46,USA-VA,1074,918,766,678,624,581,550,525,500,465,453,396,329,267,209,190,178,146,136
47,USA-VT,830,737,566,423,325,245,190,128,104,94,82,58,50,42,37,34,31,29,29
48,USA-WA,1274,1020,828,549,386,271,211,163,137,120,107,101,108,116,155,190,227,262,289
49,USA-WI,533,464,388,334,305,284,273,259,238,223,203,166,147,140,152,167,174,183,195
50,USA-WV,117,106,92,82,75,73,66,52,46,44,46,43,40,38,38,27,30,33,36
51,USA-WY,41,28,20,16,15,15,12,6,6,4,5,4,4,3,2,2,2,2,2